package com.example.crudproject.controller;


import com.example.crudproject.model.Person;
import com.example.crudproject.repository.PersonRepository;
import com.example.crudproject.service.PersonServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonRepository personRepository;
    private PersonServiceImpl personService;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String fName
            , @RequestParam String lName, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Person n = new Person();
        n.setFirstName(fName);
        n.setLastName(lName);
        n.setEmail(email);
        personRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public ResponseEntity<List<Person>> getAllTodos() {
        // This returns a JSON or XML with the users
        //return personRepository.findAll();
        List<Person> persons = personService.getPersons();
        return new ResponseEntity<>(persons, HttpStatus.OK);
    }


}